import Head from "next/head";
import Image from "next/image";
import * as Style from "../styles/style";

export default function Home() {
  return (
    <>
      <Head>
        <title>Spider Man</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Style.Principal>
        <Image
          width={500}
          height={500}
          src="/predios.svg"
          alt="img"
          responsive
        />
        <Image width={500} height={500} src="/teia.svg" alt="img" responsive />
        <Image width={500} height={500} src="/teia2.svg" alt="img" responsive />
      </Style.Principal>
      <Style.Historia>
        <div>
          <Image width={500} height={500} src="/hq.png" alt="img" />
          <p>
            Há exatos 50 anos, o Homem-Aranha (Spider-Man), personagem da Marvel
            Comics, apareceu pela primeira vez. Em agosto de 1962, na décima
            quinta (e última) edição da revista Amazing Fantasy, surgia o
            super-herói aracnídeo criado por três monstros sagrados dos
            quadrinhos: Stan Lee, Jack Kirby e Steve Ditko.
          </p>
        </div>
        <div>
          <Image width={500} height={500} src="/stan.png" alt="img" />
          <p>
            Stan Lee foi o criador do conceito e roteirista das primeiras
            histórias do Homem-Aranha. Ao seu lado estava Jack Kirby, que
            participou do desenvolvimento inicial do Escalador de Paredes, mas
            nunca chegou a ser desenhista regular do herói, papel este que coube
            a Steve Ditko, o principal desenhista de tramas de mistério e
            suspense da Marvel e corroteirista de várias das histórias de Lee
            com o Homem-Aranha.
          </p>
        </div>
      </Style.Historia>
      <Style.Filmes>
        <p>
          Lorem, ipsum dolor sit amet consectetur adipisicing elit.
          Necessitatibus ea repellat voluptates neque rem magni quis veritatis
          eos enim reiciendis temporibus dolorum, hic illum vel nulla optio
          eligendi ipsum. Praesentium.
        </p>
      </Style.Filmes>
    </>
  );
}
